# Generated by Django 3.1.4 on 2021-02-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200501_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='state',
        ),
        migrations.AddField(
            model_name='projects',
            name='staff',
            field=models.CharField(max_length=120, null=True, verbose_name='Staff tecnologico'),
        ),
        migrations.AddField(
            model_name='projects',
            name='subtitle',
            field=models.CharField(max_length=50, null=True, verbose_name='Subtitulo'),
        ),
    ]
