# Generated by Django 3.0.5 on 2020-05-01 20:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects', verbose_name='Imagen')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo')),
                ('state', models.CharField(max_length=50, verbose_name='Estado')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descripcion')),
                ('link', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['created'],
            },
        ),
    ]
