# Generated by Django 3.0.5 on 2020-05-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['ordering', 'created'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AddField(
            model_name='projects',
            name='ordering',
            field=models.SmallIntegerField(default=0, verbose_name='Orden'),
        ),
    ]
