# Generated by Django 3.1.4 on 2021-03-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210207_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='screen',
            field=models.ImageField(blank=True, null=True, upload_to='projects', verbose_name='Screen imagen'),
        ),
    ]
