# Generated by Django 3.0.5 on 2020-05-04 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, null=True, verbose_name='Año')),
                ('datetime', models.DateTimeField(blank=True, verbose_name='Datetime')),
                ('text_time', models.CharField(max_length=6, verbose_name='Fecha')),
                ('title', models.TextField(blank=True, verbose_name='Titulo')),
                ('ordering', models.SmallIntegerField(default=0, verbose_name='Orden')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ['ordering', 'created'],
            },
        ),
    ]
