# Generated by Django 3.0.5 on 2020-05-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_blog_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-ordering', 'created'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Año'),
        ),
    ]
