# Generated by Django 3.0.5 on 2020-05-04 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200503_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='ordering',
            field=models.FloatField(default=0, verbose_name='Orden'),
        ),
    ]
