# Generated by Django 3.0.7 on 2020-07-03 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200702_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='datetime',
        ),
    ]
