# Generated by Django 3.1.4 on 2021-03-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200703_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, verbose_name='Titulo')),
                ('subtitle', models.CharField(blank=True, default='Nea', max_length=20, verbose_name='Subtitulo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('link', models.URLField(blank=True, null=True)),
                ('ordering', models.FloatField(default=0, verbose_name='Orden')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
        ),
    ]
