# Generated by Django 3.0.7 on 2020-06-29 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200628_2335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certifications',
            new_name='Certificates',
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-ordering', 'created'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blog'},
        ),
        migrations.AlterModelOptions(
            name='certificates',
            options={'ordering': ['-ordering', 'created'], 'verbose_name': 'Certificate', 'verbose_name_plural': 'Certificates'},
        ),
    ]
