# Generated by Django 3.1.4 on 2021-03-11 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_docs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docs',
            options={'ordering': ['-ordering', 'created'], 'verbose_name': 'Docs', 'verbose_name_plural': 'Docs'},
        ),
    ]
