# Generated by Django 3.2.3 on 2021-05-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_curriculum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculum',
            options={'verbose_name': 'Curriculum', 'verbose_name_plural': 'Curriculum'},
        ),
        migrations.AddField(
            model_name='curriculum',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Titulo'),
        ),
    ]
