# Generated by Django 3.0.5 on 2020-05-01 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['created'], 'verbose_name': 'About'},
        ),
    ]
